### ISSUE TITLE
Create Products Model for Database

### ISSUE THREAD

**Issue by rtwhitfield84** [Ambiguous-Squids/bangazon-api#15]
Create Products Model 

## Context
Create products model in the models.py folder

## Steps to Reproduce
Products model should have the following:
1. name
2. description
3. price
4. FK: idProductTypes
5. FK: idCustomers
6. FK:idOrders

## Context
This will create the Products model in Python for access in the DB

## Your Environment
* go into root folder
*cd into bangazon-api folder
*update models.py with the products model

**Comment by danirenae** [comment]
This was reopened and completed.
