### ISSUE TITLE
Create Orders Model for Database

### ISSUE THREAD

**Issue by rtwhitfield84** [Ambiguous-Squids/bangazon-api#18]
Create Orders Model

##Context

Create Orders model in the models.py folder

##Steps to Reproduce

Orders model should have the following:
1. active
2. FK: idCustomers
3. FK: idPaymentType

This will create the Orders model in Python for access in the DB

##Your Environment

go into root folder
*cd into bangazon-api folder
*update models.py with the orders model

**Comment by danirenae** [comment]
This was reopened and completed.
